# Упражнения к занятию "Введение в NumPy и базовые операции"

Создайте массив из чисел от 1 до 20 (используйте функцию arange). Выведите его форму, размер и тип данных.

In [1]:
import numpy as np

In [8]:
a = np.arange(0, 20)
print ('Форма:', a.shape)
print ('Размер:', a.ndim)
print ('Тип данных:', a.dtype)

Форма: (20,)
Размер: 1
Тип данных: int32


Создайте массив из списка [1, 2, 3, 4, 5] и выполните следующие операции:

- Прибавьте к каждому элементу массива число 2.
- Умножьте каждый элемент массива на 3.
- Разделите каждый элемент массива на 2.
- Возведите каждый элемент в квадрат.
- Вычислите натуральный логарифм каждого элемента.

In [12]:
a = np.arange(1, 6)
print ('1)', a+2)
print ('2)', a*3)
print ('3)', a/2)
print ('4)', a**2)
print ('5)', np.log(a))

1) [3 4 5 6 7]
2) [ 3  6  9 12 15]
3) [0.5 1.  1.5 2.  2.5]
4) [ 1  4  9 16 25]
5) [0.         0.69314718 1.09861229 1.38629436 1.60943791]


3. Создайте массив из чисел от 0 до 9 (используйте функцию arange). Выполните следующие операции:

- Выведите третий элемент массива.
- Выведите элементы массива с индексами от 2 до 5 (не включая 5).

In [15]:
a = np.arange(0, 10)
print("третий элемент:", a[2])
print("индексы 2-5:", a[2:5])


третий элемент: 2
индексы 2-5: [2 3 4]


4. Создайте массив из чисел от 0 до 99 с шагом 0.5 (используйте функцию arange). Выполните следующие операции:

- Выведите его размер
- Выведите двадцать третий элемент массива.
- Выведите элементы массива с индексами от 12 до 25 (не включая 25).

In [18]:
a = np.arange(0, 99, 0.5)
print ('Размер:', a.ndim)
print ('23 элемент:', a[22])
print ('индексы 12-25:', a[12:25])

Размер: 1
23 элемент: 11.0
индексы 12-25: [ 6.   6.5  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12. ]


5. Создайте массив из 20 элементов, равномерно распределенных в диапазоне от 0 до 10, включая число 10 (используйте np.linspace). 
Выполните следующие операции:

- Выведите его размер
- Выведите пятый элемент массива.
- Выведите элементы массива с индексами от 6 до 13 (не включая 13).


In [19]:
a = np.linspace(0, 10, 20)
print ('Размер:', a.ndim)
print ('5 элемент:', a[4])
print ('индексы 6-13:', a[6:13])

Размер: 1
5 элемент: 2.1052631578947367
индексы 6-13: [3.15789474 3.68421053 4.21052632 4.73684211 5.26315789 5.78947368
 6.31578947]


6. Создайте массив из 20 элементов, равномерно распределенных в диапазоне от 0 до 10, невключая число 10 (используйте np.linspace). 
Выполните следующие операции:

- Выведите его размер
- Выведите пятый элемент массива.
- Выведите элементы массива с индексами от 6 до 13 (не включая 13).

In [20]:
a = np.linspace(0, 10, 20, endpoint=False)
print ('Размер:', a.ndim)
print ('5 элемент:', a[4])
print ('индексы 6-13:', a[6:13])

Размер: 1
5 элемент: 2.0
индексы 6-13: [3.  3.5 4.  4.5 5.  5.5 6. ]


7. Создайте двумерный массив размером 3x3, заполненный числами от 1 до 9. Выведите его форму, размер и тип данных.

In [31]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print ('Форма:', a.shape)
print ('Размер:', a.ndim)
print ('Тип данных:', a.dtype)

Форма: (3, 3)
Размер: 2
Тип данных: int32


8. Создайте двумерный массив размером 3x3, заполненный числами от 1 до 9. Выполните следующие операции:

- Выведите форму массива.
- Выведите транспонированную версию массива.
- Измените форму массива на 9x1 и выведите результат. Подсказка: метод `.reshape(5, 5)` меняет форму массива на 5x5.

In [33]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print ('Форма:', a.shape)
print ('Транспонированная версия', a.T)
print ('reshape', a.reshape(9,1))

Форма: (3, 3)
Транспонированная версия [[1 4 7]
 [2 5 8]
 [3 6 9]]
reshape [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


9. Создайте квадратную матрицу размером 4x4, заполненную числами от 1 до 16. Получите главную диагональ этой матрицы.

In [38]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print (np.diag(a, k=0))

[ 1  6 11 16]


10. Создайте матрицу размером 4×4, заполненную числом 7. Извлеките главную диагональ и диагональ, расположенную на одну позицию выше главной.

In [40]:
a = np.full((4,4), 7)
print ('Главная диагональ:', np.diag(a, k=0))
print ('Диагональ +1:', np.diag(a, k=1))

Главная диагональ: [7 7 7 7]
Диагональ +1: [7 7 7]


11. Создайте матрицу размером 3x3, заполненную нулями. Замените элементы на главной диагонали на единицы.

In [44]:
a = np.zeros((3, 3))
np.fill_diagonal(a, 1)
print (a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. Создайте матрицу размером 4x4, заполненную числами от 1 до 16. Вычислите сумму элементов на главной диагонали.

In [47]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print (np.diag(a, k=0).sum())

34


13. Создайте матрицу размером 3x3, заполненную числами от 1 до 9. Вычислите произведение элементов на главной диагонали.


In [50]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print (np.diag(a, k=0).prod())

45


14. Создайте матрицу Вандермонда для вектора [1, 2, 3, 4, 5]. Извлеките главную диагональ и диагональ, расположенную на две позиции ниже главной.

In [53]:
x = np.array([1, 2, 3, 4, 5])
a = np.vander(x)
print ('1 выше:', np.diag(a, k=0))
print ('2 ниже:', np.diag(a, k=-2))

1 выше: [1 8 9 4 1]
2 ниже: [81 64 25]


15. Создайте блочную матрицу размером 8×8, состоящую из четырех различных блоков:

- Верхний левый блок 4×4: единичная матрица

- Верхний правый блок 4×4: матрица, заполненная числом 3

- Нижний левый блок 4×4: матрица, заполненная числом 5

- Нижний правый блок 4×4: матрица Вандермонда для вектора [1, 2, 3, 4]

Извлеките главную диагональ и диагональ, проходящую через все четыре блока.

In [85]:
x = np.array([1,2,3,4])
a1b1 = np.eye(4)
a1b2 = np.full((4,4), 3)
a2b1 = np.full((4,4), 5)
a2b2 = np.vander(x)
a = np.block([[a1b1, a1b2], [a2b1, a2b2]])
print ('главная диагональ:', np.diag(a, k=0))
print ('первый вариант:', np.diag(a,k=-1), np.diag(a,k=0), np.diag(a,k=+1))
print ('второй вариант:', np.array([np.diag(a,k=-1),
                                    np.diag(a,k=+1)]))

главная диагональ: [1. 1. 1. 1. 1. 4. 3. 1.]
первый вариант: [0. 0. 0. 5. 8. 9. 4.] [1. 1. 1. 1. 1. 4. 3. 1.] [0. 0. 0. 3. 1. 2. 1.]
второй вариант: [[0. 0. 0. 5. 8. 9. 4.]
 [0. 0. 0. 3. 1. 2. 1.]]
